### ISSUE TITLE
聊天提示 conversation uuid error

### ISSUE THREAD

**Issue by hongwazi** [moyangzhan/langchain4j-aideepin#15]
有个小问题：注册邮件发送失败，数据库数据未回滚；我手工修改了user表的状态，发送消息提示 conversation uuid error。
java.lang.IllegalArgumentException: conversation uuid error
	at com.moyz.adi.common.validator.AskReqValidator.isValid(AskReqValidator.java:30)
	at com.moyz.adi.common.validator.AskReqValidator.isValid(AskReqValidator.java:11)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateSingleConstraint(ConstraintTree.java:180)

**Comment by hongwazi** [comment]
我看了下，这个uuid是default，是不是哪里不对？

**Comment by moyangzhan** [comment]
`注册邮件发送失败，数据库数据未回滚`
这个是故意这样设计的，以便可以重新发送邮件

`我手工修改了user表的状态，发送消息提示 conversation uuid error`
激活用户时会创建一个默认的会话，如果手动修改用户成激活状态，这个会话需要也手动创建才行，创建默认会话的逻辑在这里：
`ConversationService.createDefault`
