### ISSUE TITLE
用百度模型ernie speed提示下面错误

### ISSUE THREAD

**Issue by zhangjin123333** [moyangzhan/langchain4j-aideepin#27]
2024-07-17 17:08:07.648 ERROR [OkHttp https://aip.baidubce.com/...] com.moyz.adi.common.interfaces.AbstractLLMService stream error

java.lang.IllegalStateException: Invalid content-type: application/json
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:60)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by zhangjin123333** [comment]
作者能联系我么，我对这个项目感兴趣，愿意付费请教，58624951@qq.com

**Comment by moyangzhan** [comment]
@zhangjin123333 确实是有这个问题，下班后我再把新代码推上去，大概6点多~

**Comment by l269438** [comment]
有微信交流群吗

**Comment by moyangzhan** [comment]
代码已经提交，见2.8.1 @zhangjin123333

**Comment by moyangzhan** [comment]
> 有微信交流群吗

没有的，暂时不打算建群，没那么多时间在线回复的~~

**Comment by zhangjin123333** [comment]
谢谢
