### ISSUE TITLE
如果开启上下文理解，无论选择哪个模型都会出现下面的问题

### ISSUE THREAD

**Issue by zhangjin123333** [moyangzhan/langchain4j-aideepin#28]
2024-07-18 18:56:03.686 INFO [http-nio-9999-exec-5] com.moyz.adi.common.base.ResponseWrapper result:true
2024-07-18 18:56:10.223 INFO [mainExecutor-2] com.moyz.adi.common.service.ConversationMessageService asyncCheckAndPushToClient,userId:2
2024-07-18 18:56:10.311 INFO [mainExecutor-2] com.moyz.adi.common.interfaces.AbstractLLMService sseChat,messageId:afd192893aab4ab4a6e4cf4153cc0e08
2024-07-18 18:56:10.321 INFO [mainExecutor-2] com.moyz.adi.common.util.MapDBChatMemoryStore chat memory path:D:/data/chat_memory/
2024-07-18 18:56:10.333 ERROR [mainExecutor-2] org.springframework.aop.interceptor.SimpleAsyncUncaughtExceptionHandler Unexpected exception occurred invoking async method: public void com.moyz.adi.common.service.ConversationMessageService.asyncCheckAndPushToClient(org.springframework.web.servlet.mvc.method.annotation.SseEmitter,com.moyz.adi.common.entity.User,com.moyz.adi.common.dto.AskReq)

java.lang.NoClassDefFoundError: kotlin/enums/EnumEntriesKt
	at org.mapdb.DBMaker$StoreType.<clinit>(DBMaker.kt:35)
	at org.mapdb.DBMaker.fileDB(DBMaker.kt:50)
	at com.moyz.adi.common.util.MapDBChatMemoryStore.<init>(MapDBChatMemoryStore.java:31)

**Comment by moyangzhan** [comment]
这个问题有点奇怪，你是本地DEBUG时碰到的吗？发一下JDK版本、操作系统版本信息

而且mapdb官方那里也有人报了这个问题，可以顺便跟踪下~：https://github.com/jankotek/mapdb/issues/1042

**Comment by zhangjin123333** [comment]
JDK17，win11

**Comment by moyangzhan** [comment]
刚拆了jar，发现编译出来的kotlin-stdlib-1.7.22.jar是没有kotlin/enums/EnumEntriesKt这个类，倒是kotlin-stdlib-2.0.jar是有的，可以试试将kotlin-stdlib升级成2.0试试

![image](https://github.com/user-attachments/assets/0c5417a3-61ff-449a-ada2-2a89b0bde276)

**Comment by zhangjin123333** [comment]
<dependency>
             <groupId>org.jetbrains.kotlin</groupId>
                    <artifactId>kotlin-stdlib</artifactId>
            <version>2.0.0</version>
        </dependency>
        添加这个就没问题
