### ISSUE TITLE
知识库上传，没有上传成功

### ISSUE THREAD

**Issue by zhangjin123333** [moyangzhan/langchain4j-aideepin#29]
2024-07-18 21:30:26.793 INFO [http-nio-9999-exec-4] com.moyz.adi.common.base.ResponseWrapper result:com.baomidou.mybatisplus.extension.plugins.pagination.Page@85b93a6
2024-07-18 21:31:00.254 ERROR [http-nio-9999-exec-9] com.moyz.adi.common.service.KnowledgeBaseService upload error

java.lang.IllegalArgumentException: 'D:\data\images\8e95ed67100a4d8d926314f403d42912.txt' is not a file
local:
  files: D:/data/files/
  images: D:/data/images/
  tmp-images: D:/data/tmp_images/
  chat-memory: D:/data/chat_memory/
这些配置都有的，错误在下面行
	at dev.langchain4j.internal.Exceptions.illegalArgument(Exceptions.java:19)
	at dev.langchain4j.data.document.loader.FileSystemDocumentLoader.loadDocument(FileSystemDocumentLoader.java:52)
	at dev.langchain4j.data.document.loader.FileSystemDocumentLoader.loadDocument(FileSystemDocumentLoader.java:88)

**Comment by moyangzhan** [comment]
文件是否已经损坏了？

**Comment by ChaseAfterLight** [comment]
同问题，求解答

**Comment by moyangzhan** [comment]
如果方便的话，把无法上传的文件带到评论里，我试试能不能重现

**Comment by ChaseAfterLight** [comment]
@zhangjin123333  刚刚解决了 1.权限问题 2.路径不正确，找不到文件
