### ISSUE TITLE
使用ERNIE-Speed-8K聊天界面返回  系统提示：Invalid content-type: application/json

### ISSUE THREAD

**Issue by chenbinghong1005** [moyangzhan/langchain4j-aideepin#32]
在用户端聊天界面，使用ERNIE-Speed-8K，发送文字，后台日志如下：
2024-07-25 19:49:42.009 INFO [mainExecutor-2] com.moyz.adi.common.service.ConversationMessageService asyncCheckAndPushToClient,userId:1
2024-07-25 19:49:42.016 INFO [mainExecutor-2] com.moyz.adi.common.interfaces.AbstractLLMService sseChat,messageId:05d226f8b8f44e3888e14e4f717c85e0
2024-07-25 19:49:42.669 ERROR [OkHttp https://aip.baidubce.com/...] com.moyz.adi.common.interfaces.AbstractLLMService stream error

java.lang.IllegalStateException: Invalid content-type: application/json
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:60)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

2024-07-25 19:49:42.671 INFO [http-nio-9999-exec-10] com.moyz.adi.common.helper.SSEEmitterHelper response complete,uid:1

2024-07-25 19:55:23.654 INFO [mainExecutor-2] com.moyz.adi.common.service.ConversationMessageService asyncCheckAndPushToClient,userId:1
2024-07-25 19:55:23.660 INFO [mainExecutor-2] com.moyz.adi.common.interfaces.AbstractLLMService sseChat,messageId:05d226f8b8f44e3888e14e4f717c85e0
2024-07-25 19:55:23.967 ERROR [OkHttp https://aip.baidubce.com/...] com.moyz.adi.common.interfaces.AbstractLLMService stream error

java.lang.IllegalStateException: Invalid content-type: application/json
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:60)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

2024-07-25 19:55:23.970 INFO [http-nio-9999-exec-4] com.moyz.adi.common.helper.SSEEmitterHelper response complete,uid:1

我发现qianfan的baseurl：aip.baidubce.com禁止访问，不确定是不是和这个有关系。
<img width="475" alt="微信图片_20240725195816" src="https://github.com/user-attachments/assets/cd0c98df-c79e-4a26-9ac9-6ca1b7fb63bb">
还是说下面这个接口里面的功能有问题：
![微信图片_20240725195951](https://github.com/user-attachments/assets/3bda1008-9b3f-4d29-9d6d-e1b986c58fe2)

![微信图片_20240725200002](https://github.com/user-attachments/assets/901f6342-8c3e-4369-9c34-11961c87adf6)

**Comment by 1011641270** [comment]
https://github.com/moyangzhan/langchain4j-aideepin/issues/30  你可以看下我遇到的错误
