### ISSUE TITLE
知识库问答

### ISSUE THREAD

**Issue by nemolig** [moyangzhan/langchain4j-aideepin#35]
![image](https://github.com/user-attachments/assets/639c2f47-4cb4-4f3b-b108-937a01e83370)
![image](https://github.com/user-attachments/assets/4f4e0861-bcb3-46be-b484-2f579a6e12e2)
最新java代码接口接收的是qaRecordUuid，用户端传输的是kbUuid，导致知识库对话报错
2024-08-19 17:04:56.905 ERROR [mainExecutor-23] org.springframework.aop.interceptor.SimpleAsyncUncaughtExceptionHandler Unexpected exception occurred invoking async method: public void com.moyz.adi.common.service.KnowledgeBaseService.retrieveAndPushToLLM(com.moyz.adi.common.entity.User,org.springframework.web.servlet.mvc.method.annotation.SseEmitter,java.lang.String)

com.moyz.adi.common.exception.BaseException: A0017:数据不存在
	at com.moyz.adi.common.service.KnowledgeBaseQaRecordService.getOrThrow(KnowledgeBaseQaRecordService.java:120)
	at jdk.internal.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at com.moyz.adi.common.service.KnowledgeBaseQaRecordService$$SpringCGLIB$$0.getOrThrow(<generated>)
	at com.moyz.adi.common.service.KnowledgeBaseService.retrieveAndPushToLLM(KnowledgeBaseService.java:365)
	at jdk.internal.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by nemolig** [comment]
大佬 gitee没一起更新吗？
