### ISSUE TITLE
用通义千问的key出现下面错误

### ISSUE THREAD

**Issue by zhangjin123333** [moyangzhan/langchain4j-aideepin#45]
2024-11-16 09:30:55,814 INFO (ConversationMessageService.java:110)- asyncCheckAndPushToClient,userId:2
2024-11-16 09:31:23,307 INFO (AbstractLLMService.java:142)- sseChat,messageId:null
2024-11-16 09:31:23,509 ERROR (AbstractLLMService.java:215)- stream error
com.alibaba.dashscope.exception.ApiException: {"statusCode":403,"message":"Forbidden","code":"response_error","isJson":true}
	at com.alibaba.dashscope.protocol.okhttp.OkHttpHttpClient$3.onFailure(OkHttpHttpClient.java:337)
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:52)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2024-11-16 09:31:23,513 INFO (SSEEmitterHelper.java:118)- response complete,uid:2

**Comment by moyangzhan** [comment]
用的是哪个模型？需要先确保在通义的测试界面是可以调用该模型的~  后面可以把完整的错误堆栈贴出来
