### ISSUE TITLE
千帆模型不可用

### ISSUE THREAD

**Issue by Hwongyohong** [moyangzhan/langchain4j-aideepin#8]
作者在引用千帆模型时是否有Invalid content-type: application/json 的报错？

**Comment by moyangzhan** [comment]
我接千帆时挺顺利的，是否可以贴一下错误堆栈

**Comment by Hwongyohong** [comment]
2024-04-21 00:07:17.518 ERROR [OkHttp https://aip.baidubce.com/...] com.moyz.adi.common.interfaces.AbstractLLMService stream error

java.lang.IllegalStateException: Invalid content-type: application/json
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:60)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2024-04-21 00:07:17.521 INFO [http-nio-9999-exec-1] com.moyz.adi.common.helper.SSEEmitterHelper response complete,uid:1
模型是：ERNIE-Bot-8K，另外ERNIE-Bot 4.0是可以的，猜测是langchain4j的问题，你可以测试下

**Comment by moyangzhan** [comment]
@Hwongyohong 刚去查了下文档，会不会是因为ERNIE-Bot-8K已经下线了？来源：https://cloud.baidu.com/doc/WENXINWORKSHOP/s/6lp69is2a
![image](https://github.com/moyangzhan/langchain4j-aideepin/assets/83471894/76e0f829-6497-402b-b52e-11a7d24ec6f2)
